#ifndef CXURITY_SRC_UI_UICOMMON_H_
#define CXURITY_SRC_UI_UICOMMON_H_

inline long long CXU_RAYLIB_ORG_WNDPROC;
inline void* CXU_WIN_HANDLE;
inline Texture CXU_APP_TEXTURES[10];

#endif  //CXURITY_SRC_UI_UICOMMON_H_
