#ifndef CXURITY_SRC_HEADERS_GLOBALSTATE_H_
#define CXURITY_SRC_HEADERS_GLOBALSTATE_H_


inline const char* CXU_ROLE_NAMES[4]{"ADMIN", "USER", "UNSET", "SERVER"};


#endif  //CXURITY_SRC_HEADERS_GLOBALSTATE_H_
